### ISSUE TITLE
Add Issue and PR templates to the repository

### ISSUE THREAD

**Issue by sanskriti2005** [Sanskriti1102/CourseGuard#1]
Hello CourseGuard!

To make it easier for contributors to raise issues and pull requests (PRs) in a consistent way, I suggest adding templates for both. These templates will guide contributors by providing a clear format to follow, which will help maintainers manage and review issues and PRs more efficiently. The templates will also ensure that important information is provided from the start, making it quicker to address contributions.

Please assign me to this issue, I would love to work on this!

**Comment by Krishi1211** [comment]
You have been assigned please complete it within 1 week

**Comment by sanskriti2005** [comment]
@Krishi1211 Hi, I just realized I missed this earlier—could you please add the 'WoB' labels to this and the PR? Thanks!
