### ISSUE TITLE
Navbar Component

### ISSUE THREAD

**Issue by Krishi1211** [Sanskriti1102/CourseGuard#15]
Refer Home 1.0 slide for the navbar. Create a importable component so that it can be used every where.
https://www.figma.com/design/DWokUT7bGtMrDVSyj7bp7l/Digiaccel---E-Learning-Platform-(Community)?node-id=5734-14661&t=NxXBNrYk4gzODMg9-1

**Comment by sanskriti2005** [comment]
Hello! Can I be assigned to this?

**Comment by Krishi1211** [comment]
assigned
