### ISSUE TITLE
Request to add CODE OF CONDUCT

### ISSUE THREAD

**Issue by neyhere07** [Sanskriti1102/CourseGuard#2]
A Code of Conduct helps to establish clear guidelines for expected behavior within the community, ensuring that it remains inclusive, respectful, and productive for everyone involved.

Here are some reasons why adding a Code of Conduct is important:

(i) It promotes respectful and constructive interactions between contributors.
(ii) It ensures that all contributors feel welcomed and included, regardless of their background or experience.
(iii) It helps maintain a positive community environment, encouraging collaboration.

[Contributor Covenant](https://www.contributor-covenant.org/) is widely adopted for open source projects.

**Comment by neyhere07** [comment]
Hello Admin and Mentor, I'm a WOB Contributor-2024. I would like to add Code of Conduct to this repository. Please assign this issue to me. Thank you!

**Comment by Krishi1211** [comment]
Hii @neyhere07 Its been added already.
